### ISSUE TITLE
Cannot change description

### ISSUE THREAD

**Issue by brodecva** [odalic/odalic-ui#125]
It is kind a hit back. Allow changing and saving the description.

**Comment by istvan-satmari** [comment]
Done; sorry for misunderstanding.

**Comment by brodecva** [comment]
> Done; sorry for misunderstanding.

Still not working. Just create a task (not use even the Create and run, just Create), show the list, then edit the configuration, click Save, and the task description remains the same, even when edited again.

Commit used: https://github.com/odalic/odalic-ui/commit/7820fc01a58f1c02c88f31c192aca132805972b4

**Comment by istvan-satmari** [comment]
Did that, retested, and is working. => are we talking about the same description field (right below a task's name and the one displayed in the task config table?)

**Comment by brodecva** [comment]
> Did that, retested, and is working. => are we talking about the same description field (right below a task's name and the one displayed in the task config table?)

You are right, taken back. Sorry about that.

**Comment by istvan-satmari** [comment]
np
