### ISSUE TITLE
Cannot add new relation - own relation disabled

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-ui#86]
Running task using the file and latest develop (7. 9. morning): 
[Books-v2.csv.zip](https://github.com/odalic/odalic-ui/files/458639/Books-v2.csv.zip)

Then go to relations step. Click "Link creation". Create link e.g. between author and series. Now I cannot define the link, because "own relation" is disabled:

![screen shot 2016-09-07 at 12 54 33](https://cloud.githubusercontent.com/assets/3014917/18309639/b596eb48-74fa-11e6-9db5-c9c364f4bb41.png)

Solution: For relations, it must be possible to define custom (own) relations, because otherwise it is not possible to create new edges/demonstrate the features of the graph.

**Comment by tomas-knap** [comment]
Maybe caused by solving #78 .

**Comment by brodecva** [comment]
@tomas-knap You are right, @KataBoku please fix it as soon as possible.

**Comment by brodecva** [comment]
Fixed as of #88 .

**Comment by tomas-knap** [comment]
Tested on: 72de95488cf87b91f283b9a9a6f905379a61acb5
But still does not work. When I add new edge, dialog appears, but I cannot add own relation:

![screen shot 2016-09-09 at 16 22 01](https://cloud.githubusercontent.com/assets/3014917/18390265/ca912fda-76a9-11e6-8e72-c865c86ba945.png)

**Comment by tomas-knap** [comment]
It is working
